mongodb:
  server:   localhost
  database: uptime
  user:     root 
  password:

monitor:
  name:                   origin
  apiUrl:                 'http://localhost:8082/api'
  pollingInterval:        10000      # ten seconds
  timeout:                8000       # eight seconds
  userAgent:              NodeUptime/1.3 (https://github.com/fzaninotto/uptime)

analyzer:
  updateInterval:         86400000 #daily      # 60000 = one minute
  qosAggregationInterval: 86400000 #daily
  pingHistory:            2678400000 # one month

autoStartMonitor: true

server:
  port:     8082

verbose: true # only used in dev